### ISSUE TITLE
Hyperlinks not linking to correct pages

### ISSUE THREAD

**Issue by isamardzija** [payloadcms/website#107]
Hi!

I noticed what I think are some issues with hyperlinks.

- On [Use Cases/Websites](https://payloadcms.com/use-cases/websites) hyperlinks "MORE ABOUT BLOCKS" and "RICH TEXT DOCS" are both linking to https://payloadcms.com/use-cases/websites instead of their pages in the docs
- On the [Textarea Field docs](https://payloadcms.com/docs/fields/textarea) under the "Config" heading, there is a double "More" hyperlink next to the description of the `defaultValue` option

**Comment by JessChowdhury** [comment]
Hey @isamardzija, thank you for catching these!

1. The button wasn't returning the right url here, pushed a fix
2. Double link typo also fixed

These changes will live soon 👍
