### ISSUE TITLE
Docs navigation is broken on mobile 

### ISSUE THREAD

**Issue by maxmorozoff** [payloadcms/website#126]
Hello!

Mobile version of docs' TOC doesn't work. 

Firefox:

https://user-images.githubusercontent.com/66020883/229647391-2a523f35-6437-4980-bf63-c12b651d90b1.mp4

Chrome:

https://user-images.githubusercontent.com/66020883/229647392-c7dd014a-d568-426d-9c88-8a72b8e91dec.mp4

**Comment by choutkamartin** [comment]
Fixed by https://github.com/payloadcms/website/commit/eca428b235b9284e2ade03ab49a800759dc4bb3f

**Comment by maxmorozoff** [comment]
Pull request #131 fixes these issues: 

![image](https://user-images.githubusercontent.com/66020883/230178310-10c6a16a-4992-4b39-8b73-53ed0f453c72.png)

![image](https://user-images.githubusercontent.com/66020883/230178123-e3929778-e1ef-4e8a-be16-4fabcbbfdc45.png)
