### ISSUE TITLE
Community help - Some broken links

### ISSUE THREAD

**Issue by iamlinkus** [payloadcms/website#130]
Looks like discord entries are broken on the community help page, even though they're shown in search results.

Some examples:
https://payloadcms.com/community-help/discord/struggling-with-authentication - is listed in the search, but throws a 500.
https://payloadcms.com/community-help/discord/poor-mans-deployment - is listed, but throws a 404.

**Comment by iamlinkus** [comment]
Looks like it works again, after the new blog post everything works as expected (cache problem maybe?).

**Comment by PatrikKozak** [comment]
Hey @iamlinkus - Looks like some of the discord link's titles were not updating after the author had updated their threads title. This has been fixed!

In regards to the 500s, we have periodically seen these issues with the app folder and will continue looking out for this - but as of right now, everything is working as expected.

Thank you for pointing these links out!
