### ISSUE TITLE
Empty links on homepage

### ISSUE THREAD

**Issue by alexcarpenter** [payloadcms/website#141]
Noticed a couple of empty links on the homepage, causing extra tab stops with no information to the user.

![CleanShot 2023-04-14 at 09 19 27@2x](https://user-images.githubusercontent.com/825855/232055124-eba3120b-080d-4fd8-9397-dc16e97e1488.png)

**Comment by JarrodMFlesch** [comment]
@alexcarpenter Thanks! There happened to be a couple other places where empty anchor tags were appearing. It was a content issue, has been resolved now.
