### ISSUE TITLE
Deploy Branch does not default to default branch of repo

### ISSUE THREAD

**Issue by denolfe** [payloadcms/website#181]
The "Branch to deploy" field properly loads all branches available for the repo. However, it's initial value is whatever is first alphabetically. Ideally, this should default to the default branch of the repository.

<img width="259" alt="CleanShot 2023-06-19 at 14 38 00@2x" src="https://github.com/payloadcms/website/assets/65888/0d763cc2-1099-432b-ac3f-e3571590fd84">

![CleanShot 2023-06-19 at 14 38 08@2x](https://github.com/payloadcms/website/assets/65888/f9245016-7104-44c6-a102-052aa5e8f8b0)

**Comment by jacobsfletch** [comment]
Pretty sure this is fixed, need to test again.

**Comment by PatrikKozak** [comment]
@jacobsfletch Just tested this, you're right - it's fixed.
![Screen Shot 2023-08-28 at 3 22 21 PM](https://github.com/payloadcms/website/assets/35232443/ea105c39-db2e-43bc-882b-4f66180293f2)
