### ISSUE TITLE
Deployment time should include minutes

### ISSUE THREAD

**Issue by denolfe** [payloadcms/website#183]
<img width="346" alt="CleanShot 2023-06-21 at 13 53 10@2x" src="https://github.com/payloadcms/website/assets/65888/7a3b5562-b35a-48fb-bea2-5d76275c3b53">

**Comment by PatrikKozak** [comment]
![Screen Shot 2023-08-28 at 3 13 36 PM](https://github.com/payloadcms/website/assets/35232443/2154fda0-c97c-43cd-8b7f-8ebe7864c809)

Updated deployment status shows time with minutes
