### ISSUE TITLE
Elements in navbar are invisible 

### ISSUE THREAD

**Issue by Noothan-am** [payloadcms/website#193]
### Link to reproduction

https://payloadcms.com/

### To Reproduce

Just go to website url mentioned

### Describe the Bug

here you cannot see what is there in navbar so it needs to be made visible 

### Payload Version

-

**Comment by jacobsfletch** [comment]
Does this continue to happen for you when you reload the page? Roping @JarrodMFlesch in here.

**Comment by Noothan-am** [comment]
Hey @jacobsfletch, assign it to me. i will fix this issue

**Comment by Noothan-am** [comment]
> Does this continue to happen for you when you reload the page? Roping @JarrodMFlesch in here.

yes

**Comment by JarrodMFlesch** [comment]
@Noothan-am is this still happening for you? Are you zoomed in? I am unable to recreate the issue.

**Comment by Noothan-am** [comment]
> @Noothan-am is this still happening for you? Are you zoomed in? I am unable to recreate the issue.

yes 
![image](https://github.com/payloadcms/website/assets/100135382/9a4fdb22-e396-49a8-93ac-df76e69776bb)

**Comment by arvindpndit** [comment]
It is happening only when we are zoomed in (125%)
![Screenshot from 2023-09-07 21-54-37](https://github.com/payloadcms/website/assets/121677260/19150325-1335-4451-94e5-45ff4d92caaa)

in 100% zoom, it's working fine
![Screenshot from 2023-09-07 21-55-02](https://github.com/payloadcms/website/assets/121677260/8033af49-9b04-4217-bc07-4afbd6182453)
