### ISSUE TITLE
Scrollspy is not working on the Docs

### ISSUE THREAD

**Issue by notchris** [payloadcms/website#231]
Hello team Payload! Found a possible issue on the docs this morning, Scrollspy does not seem to be working correctly.

Page: All documentation pages
Reproduce: Click on the navigation links and the page will not scroll to that section.

Browser: Chrome Latest 64bit

As always, you all are the best, keep up the good work!

**Comment by notchris** [comment]
Also @paulpopus confirmed the issue on Firefox as well

**Comment by JarrodMFlesch** [comment]
Fixed. Thanks for reporting @notchris!
