### ISSUE TITLE
Active deployment details are misaligned and incorrectly sized

### ISSUE THREAD

**Issue by jacobsfletch** [payloadcms/website#241]
We need to ensure the labels are aligned and that the font sizes are all correct.

<img width="159" alt="Screenshot 2023-08-29 at 11 09 11 AM" src="https://github.com/payloadcms/website/assets/15735305/05b5078b-9902-4324-b361-6498252be984">

**Comment by muperdev** [comment]
is anyone working on it?

**Comment by JessChowdhury** [comment]
Fixed and changes deployed.
