### ISSUE TITLE
CSS duplication in admin/website. Possible performance issues?

### ISSUE THREAD

**Issue by ensidialabs** [payloadcms/website#253]
### Link to reproduction

https://payloadcms.com/cloud/settings

### To Reproduce

![css](https://github.com/payloadcms/payload/assets/105992892/b1b696ef-c3a4-46e4-b01c-2438ad7ed090)
![css2](https://github.com/payloadcms/payload/assets/105992892/017fb489-cd28-400c-b812-967444e140e0)

### Describe the Bug

We plan to use Payload in our infrastructure (a large bank). But I noticed that in many places there is duplication of CSS.
Is this the working principle of CSS Modules or is it a bug/incorrect settings?

### Payload Version

latest

**Comment by tylandavis** [comment]
I believe this is a side effect of using `@import` in multiple .scss file of the same scss module. We use a `common.scss` file to import mixins into component-level scss modules. I'm going to close this issue, as it's not much of a performance issue (only 31kb) on this route.
