### ISSUE TITLE
wrong bundler instructions

### ISSUE THREAD

**Issue by dkirchhof** [payloadcms/website#259]
Hey, just found some wrong instructions on this page: https://payloadcms.com/docs/admin/bundlers

![image](https://github.com/payloadcms/website/assets/2778643/fdbd27eb-8fda-4fda-9b5c-2cd1ddb4ff98)

I think it should be `yarn add @payloadcms/bundler-webpack` and `yarn add @payloadcms/bundler-vite`.

**Comment by JarrodMFlesch** [comment]
[This issue has been fixed](https://github.com/payloadcms/payload/pull/3523) but not released, I will rebuild the site now! Thanks
