### ISSUE TITLE
The links below the form in the auth pages don't work

### ISSUE THREAD

**Issue by namanbnsl** [payloadcms/website#273]
![image](https://github.com/payloadcms/website/assets/61648404/af6b9099-49a9-49cf-b691-d47895f1f138)

The image provided is of the sign up page.

**Comment by JessChowdhury** [comment]
Hi @namanbnsl - when you say 'links below the form' are you referring to these links in the footer?

<img width="1435" alt="Screenshot 2023-11-10 at 11 41 54 AM" src="https://github.com/payloadcms/website/assets/67977755/e3735e17-15f6-4365-a2a0-496af3c53c55">

**Comment by namanbnsl** [comment]
I am referring to the links that say `Documentation` and `Stay Connected`

**Comment by JessChowdhury** [comment]
> Documentation and Stay Connected

These are just the headings for the sections below them
