### ISSUE TITLE
Navigations color Onclick 

### ISSUE THREAD

**Issue by muperdev** [payloadcms/website#276]
![tg_image_3055276797](https://github.com/payloadcms/website/assets/85489543/68cbef24-c3f1-43a9-9355-f8d79c710a5d)

**Comment by JessChowdhury** [comment]
Hi @muperdev! It doesn't do this for me - what browser are you using?
https://github.com/payloadcms/website/assets/67977755/223728ff-b895-4956-9882-d4b00ce11b88

**Comment by muperdev** [comment]
@JessChowdhury Hi jess, mine is safari

**Comment by ridoystarlord** [comment]
@JessChowdhury I would like to contribute on this issue.
