### ISSUE TITLE
There's a broken link in Docs > Configuration > Collections > More collection config examples

### ISSUE THREAD

**Issue by kuskhan** [payloadcms/website#280]
"You can find an assortment of [example collection configs](https://github.com/payloadcms/public-demo/tree/master/src/collections) in the Public Demo source code on GitHub."
It seems like  [example collection configs](https://github.com/payloadcms/public-demo/tree/master/src/collections) has a broken link.

- https://github.com/payloadcms/public-demo/tree/master/src/collections
- 404 - page not found

**Comment by rafalnawojczyk** [comment]
I think that this issue can be closed, as it is already working properly.
