### ISSUE TITLE
Feature request: Comparision to sanity

### ISSUE THREAD

**Issue by scarf005** [payloadcms/website#292]
Hi, it'd be very helpful to also have a comparision with [sanity](https://payloadcms.com/compare), since they are [said to be similar.](https://news.ycombinator.com/item?id=32665968)

**Comment by ncaminata** [comment]
We have the full Sanity comparison posted here: [https://payloadcms.com/compare/sanity](https://payloadcms.com/compare/sanity)

You can locate others @ [payloadcms.com/compare](https://payloadcms.com/compare).
