### ISSUE TITLE
Navbar color issue

### ISSUE THREAD

**Issue by revnelson** [payloadcms/website#353]
With light mode enabled, resize window such that when you scroll all the way to the bottom (dark footer) the Navbar turns dark with white text. Scroll back to the top and the Navbar correctly returns to white. However, the text stays white.

Same behavior in Firefox and Safari.

**Comment by zanhk** [comment]
Here's a video of what happen

https://payloadcms.com/docs/rich-text/overview

[google_screen_recording_2024-03-23T22-46_37.806Z.webm](https://github.com/payloadcms/website/assets/17980844/f7af12d4-621d-4211-a42d-1e3c08a1b25e)
