### ISSUE TITLE
Describe the order of hooks

### ISSUE THREAD

**Issue by thgh** [payloadcms/website#74]
The order is probably as listed [here](https://payloadcms.com/docs/hooks/collections) but would be nice to read it explicitly.

+ in what order do field vs collection vs global hooks run?
https://payloadcms.com/docs/hooks/overview

**Comment by jacobsfletch** [comment]
Hey @thgh thanks for the request! Docs are actually written into Payload core [here](https://github.com/payloadcms/payload/tree/master/docs). We retrieve these files from GitHub and render them onto the website. But to answer your question, hooks are fired in the order they [appear in the docs](https://payloadcms.com/docs/hooks/overview), which is:

1. [beforeOperation](https://payloadcms.com/docs/hooks/collections#beforeoperation)
2. [beforeValidate](https://payloadcms.com/docs/hooks/collections#beforevalidate)
3. [beforeChange](https://payloadcms.com/docs/hooks/collections#beforechange)
4. [afterChange](https://payloadcms.com/docs/hooks/collections#afterchange)
5. [beforeRead](https://payloadcms.com/docs/hooks/collections#beforeread)
6. [afterRead](https://payloadcms.com/docs/hooks/collections#afterread)
7. [beforeDelete](https://payloadcms.com/docs/hooks/collections#beforedelete)
8. [afterDelete](https://payloadcms.com/docs/hooks/collections#afterdelete)

If you want to make a contribution to the docs, feel free to [open a PR here](https://github.com/payloadcms/payload/pulls).
