### ISSUE TITLE
Documentation - Hooks > Overview gives application error

### ISSUE THREAD

**Issue by TomSmedley** [payloadcms/website#77]
Hey guys,

Firstly let me say it's incredible what you have achieved in two weeks. It would be interesting to learn what internal processes you used to go to production to quickly.

One thing I noticed is Hooks > Overview gives an application error, unfortunately is doesn't offer much up in the error.
```js
Error: An error occurred in the Server Components render. The specific message is omitted in production builds to avoid leaking sensitive details. A digest property is included on this error instance which may provide additional details about the nature of the error.
```

EDIT:
Also affects Fields > Overview, Access Control > Overview, Authentication > Overview, Upload > Overview and REST API > Overview,

**Comment by jmikrut** [comment]
Hey @TomSmedley — thank you for the compliments!! It was a crazy couple weeks for sure.

We are a tight team that has worked together for 5+ years, and we come from an agency background where we've done this type of stuff quite frequently for years. That probably explains the efficiency more than anything. But it was still a lot for sure.

I can't replicate the Hooks > Overview 500 - can you still replicate it?

**Comment by TomSmedley** [comment]
@jmikrut You have a great team!

I'm unable to replicate it now, not exactly sure why I was getting that error but seems to have fixed itself!
