### ISSUE TITLE
Phone field country selector text not visible

### ISSUE THREAD

**Issue by lucaslcode** [payloadcms/website#85]
In dark mode:
<img width="251" alt="image" src="https://user-images.githubusercontent.com/32044095/212221198-945e9c28-2a8a-49e1-a3cc-753accb536e2.png">

Brave browser, Version 1.47.171 Chromium: 109.0.5414.87 (Official Build) (64-bit)

**Comment by JarrodMFlesch** [comment]
Took a bit for us to get back with you, but this has been resolved @lucaslcode. Thanks for reporting!
